# Generated by Django 4.2.25 on 2025-10-15 18:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20, unique=True, verbose_name='شناسه تلگرام')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری تلگرام')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='شماره تماس')),
                ('is_approved', models.BooleanField(default=False, help_text='آیا کاربر توسط ادمین تایید شده است؟', verbose_name='تأیید شده')),
                ('rial_balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی ریالی')),
                ('gold_balance_grams', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی طلا (گرم)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
                'indexes': [models.Index(fields=['telegram_id'], name='users_profi_telegra_2ee79a_idx'), models.Index(fields=['phone_number'], name='users_profi_phone_n_8821cb_idx')],
            },
        ),
    ]
