# Generated by Django 4.2.25 on 2025-10-25 18:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(db_index=True, help_text='شناسه منحصر به فرد کاربر در تلگرام', max_length=20, unique=True, verbose_name='شناسه تلگرام')),
                ('telegram_username', models.CharField(blank=True, help_text='نام کاربری کاربر در تلگرام (اختیاری)', max_length=100, null=True, verbose_name='نام کاربری تلگرام')),
                ('phone_number', models.CharField(db_index=True, help_text='شماره تماس کاربر (برای احراز هویت)', max_length=15, unique=True, verbose_name='شماره تماس')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='آیا کاربر توسط ادمین تایید شده است؟', verbose_name='تأیید شده')),
                ('rial_balance', models.DecimalField(decimal_places=0, default=0, help_text='موجودی ریالی کاربر (تومان یا ریال)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی ریالی')),
                ('gold_balance_grams', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='موجودی طلای کاربر به گرم', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی طلا (گرم)')),
                ('coin_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='موجودی سکه تمام بهار آزادی', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی سکه')),
                ('dollar_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='موجودی دلار آمریکا', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی دلار')),
                ('frozen_rial_balance', models.DecimalField(decimal_places=0, default=0, help_text='موجودی ریالی در انتظار تکمیل تراکنش', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی ریالی مسدود شده')),
                ('frozen_gold_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='موجودی طلای در انتظار تکمیل تراکنش', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی طلای مسدود شده')),
                ('frozen_coin_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='موجودی سکه در انتظار تکمیل تراکنش', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی سکه مسدود شده')),
                ('frozen_dollar_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='موجودی دلار در انتظار تکمیل تراکنش', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی دلار مسدود شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(help_text='نام کامل صاحب حساب', max_length=200, verbose_name='نام صاحب حساب')),
                ('bank_name', models.CharField(choices=[('ملی ایران', 'بانک ملی ایران'), ('ملت', 'بانک ملت'), ('تجارت', 'بانک تجارت'), ('صادرات', 'بانک صادرات'), ('سپه', 'بانک سپه'), ('رفاه', 'بانک رفاه'), ('پاسارگاد', 'بانک پاسارگاد'), ('پارسیان', 'بانک پارسیان'), ('اقتصاد نوین', 'بانک اقتصاد نوین'), ('سامان', 'بانک سامان'), ('سینا', 'بانک سینا'), ('کارآفرین', 'بانک کارآفرین'), ('آینده', 'بانک آینده'), ('شهر', 'بانک شهر'), ('دی', 'بانک دی'), ('صنعت و معدن', 'بانک صنعت و معدن'), ('توسعه تعاون', 'بانک توسعه تعاون'), ('قوامین', 'بانک قوامین'), ('مهر اقتصاد', 'بانک مهر اقتصاد'), ('حکمت ایرانیان', 'بانک حکمت ایرانیان')], max_length=50, verbose_name='نام بانک')),
                ('account_number', models.CharField(help_text='شماره شبا یا شماره کارت 16 رقمی', max_length=50, verbose_name='شماره حساب/کارت')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='آیا توسط ادمین تایید شده است؟', verbose_name='تایید شده')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این حساب برای واریز/برداشت فعال است؟', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['telegram_id'], name='users_profi_telegra_2ee79a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number'], name='users_profi_phone_n_8821cb_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_approved', '-created_at'], name='users_profi_is_appr_1c1260_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['profile', 'is_verified'], name='users_banka_profile_937577_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_verified', 'is_active'], name='users_banka_is_veri_2bd423_idx'),
        ),
    ]
