# Generated by Django 4.2.25 on 2025-10-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, help_text='کد ملی 10 رقمی', max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
