# Generated by Django 4.2.25 on 2025-10-27 18:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_wallet_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل\u200cها'},
        ),
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='users_banka_profile_937577_idx',
            old_name='users_banka_profile_idx',
        ),
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='users_banka_is_veri_2bd423_idx',
            old_name='users_banka_is_verified_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='national_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gold_balance_grams',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='موجودی طلای کاربر به گرم', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی طلا (گرم)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا کاربر توسط ادمین تایید شده است؟', verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='شماره تماس کاربر (برای احراز هویت)', max_length=15, unique=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rial_balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='موجودی ریالی کاربر (تومان یا ریال)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی ریالی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(db_index=True, help_text='شناسه منحصر به فرد کاربر در تلگرام', max_length=20, unique=True, verbose_name='شناسه تلگرام'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='نام کاربری کاربر در تلگرام (اختیاری)', max_length=100, null=True, verbose_name='نام کاربری تلگرام'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_approved', '-created_at'], name='users_profi_is_appr_1c1260_idx'),
        ),
    ]
