# Generated by Django 4.2.25 on 2025-10-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='users_banka_profile_937577_idx',
            old_name='users_banka_profile_idx',
        ),
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='users_banka_is_veri_2bd423_idx',
            old_name='users_banka_is_verified_idx',
        ),
    ]
