# Generated by Django 4.2.25 on 2025-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_banka_profile_idx_users_banka_profile_937577_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(
                choices=[('CARD', 'کارت بانکی'), ('IBAN', 'شماره شبا')],
                default='CARD',
                help_text='نوع حساب: کارت بانکی یا شماره شبا',
                max_length=4,
                verbose_name='نوع حساب'
            ),
        ),
    ]
