# Generated by Django 4.2.25 on 2025-11-02 17:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20251028_2144'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='users_banka_is_veri_2bd423_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, help_text='شماره شبای 26 رقمی (اختیاری)', max_length=26, verbose_name='شماره شبا'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_holder_name',
            field=models.CharField(help_text='نام کامل صاحب حساب', max_length=200, verbose_name='نام صاحب حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(help_text='شماره حساب 16 رقمی', max_length=16, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'حساب پس\u200cانداز'), ('CURRENT', 'حساب جاری')], default='SAVINGS', help_text='نوع حساب بانکی', max_length=10, verbose_name='نوع حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(help_text='نام بانک (مثل: ملی، ملت، سپه)', max_length=100, verbose_name='نام بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا این حساب توسط ادمین تأیید شده است؟', verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='profile',
            field=models.ForeignKey(help_text='کاربری که این حساب متعلق به اوست', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.profile', verbose_name='پروفایل کاربر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coin_balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='موجودی سکه کاربر', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی سکه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frozen_coin_balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='موجودی سکه که به دلیل برداشت در انتظار مسدود شده', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی سکه مسدود شده'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frozen_dollar_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='موجودی دلار که به دلیل برداشت در انتظار مسدود شده', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی دلار مسدود شده'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frozen_gold_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='موجودی طلا که به دلیل برداشت در انتظار مسدود شده', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی طلای مسدود شده'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frozen_rial_balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='موجودی ریالی که به دلیل برداشت در انتظار مسدود شده', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی ریالی مسدود شده'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_number'], name='users_banka_account_872377_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('profile', 'account_number'), name='unique_profile_account'),
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_active',
        ),
    ]
