# Generated by Django 4.2.25 on 2025-11-12 15:53

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_bankaccount_users_banka_is_veri_2bd423_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, help_text='کد ملی 10 رقمی', max_length=10, null=True, unique=True, validators=[users.validators.validate_iranian_national_code], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(help_text='شماره حساب 16 رقمی', max_length=16, validators=[users.validators.validate_bank_account_number], verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, help_text='شماره شبای 26 رقمی (اختیاری)', max_length=26, validators=[users.validators.validate_iranian_iban], verbose_name='شماره شبا'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='شماره تماس کاربر (برای احراز هویت)', max_length=15, unique=True, validators=[users.validators.validate_iranian_phone_number], verbose_name='شماره تماس'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['national_code'], name='users_profi_nationa_7881dd_idx'),
        ),
    ]
