# Generated by Django 4.2.25 on 2025-10-25 18:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('BUY', 'خرید از ما'), ('SELL', 'فروش به ما')], help_text='خرید از ما یا فروش به ما', max_length=4, verbose_name='نوع سفارش')),
                ('quantity_grams', models.DecimalField(decimal_places=4, help_text='مقدار طلا به گرم', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='مقدار (گرم)')),
                ('price_per_gram', models.DecimalField(decimal_places=0, help_text='قیمت هر گرم در زمان ثبت سفارش (ریال)', max_digits=12, verbose_name='قیمت هر گرم (لحظه ثبت)')),
                ('total_amount', models.DecimalField(decimal_places=0, help_text='مبلغ کل سفارش (ریال)', max_digits=15, verbose_name='مبلغ کل (ریال)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده')], db_index=True, default='PENDING', help_text='وضعیت فعلی سفارش', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('completed_at', models.DateTimeField(blank=True, help_text='زمان تکمیل سفارش', null=True, verbose_name='تاریخ تکمیل')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای داخلی برای ادمین', verbose_name='یادداشت\u200cها')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(db_index=True, help_text='شماره یونیک تراکنش', max_length=50, unique=True, verbose_name='شماره تراکنش')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'واریز وجه'), ('WITHDRAW', 'برداشت وجه'), ('TRANSFER_SEND', 'انتقال ارسالی'), ('TRANSFER_RECEIVE', 'انتقال دریافتی'), ('BUY', 'خرید'), ('SELL', 'فروش')], db_index=True, max_length=20, verbose_name='نوع تراکنش')),
                ('currency_type', models.CharField(choices=[('RIAL', 'ریال'), ('GOLD', 'طلا'), ('COIN', 'سکه'), ('DOLLAR', 'دلار')], db_index=True, max_length=10, verbose_name='نوع ارز')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='مقدار')),
                ('balance_before', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='موجودی قبل از تراکنش')),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='موجودی بعد از تراکنش')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده'), ('FAILED', 'ناموفق')], db_index=True, default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('user_note', models.TextField(blank=True, verbose_name='یادداشت کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='users.profile', verbose_name='پروفایل کاربر')),
                ('related_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.bankaccount', verbose_name='حساب بانکی مرتبط')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='trading.order', verbose_name='سفارش مرتبط')),
                ('related_user', models.ForeignKey(blank=True, help_text='برای انتقال وجه: فرستنده یا گیرنده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='users.profile', verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(choices=[('gold', 'طلای آبشده'), ('coin', 'سکه تمام'), ('dollar', 'دلار آمریکا')], db_index=True, help_text='کد یکتای محصول برای شناسایی', max_length=20, unique=True, verbose_name='کد محصول')),
                ('name', models.CharField(help_text='نام محصول (مثل: سکه بهار آزادی، طلای 18 عیار)', max_length=100, unique=True, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, help_text='به صورت خودکار از روی نام ساخته می\u200cشود', unique=True, verbose_name='اسلاگ')),
                ('buy_price', models.DecimalField(decimal_places=0, help_text='قیمت خرید هر گرم از مشتری (ریال)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت خرید ما از مشتری')),
                ('sell_price', models.DecimalField(decimal_places=0, help_text='قیمت فروش هر گرم به مشتری (ریال)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت فروش ما به مشتری')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='آیا این محصول برای معامله فعال است؟', verbose_name='فعال برای معامله')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='trading_pro_is_acti_a7c05f_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(help_text='محصول مورد معامله', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(help_text='کاربری که این سفارش را ثبت کرده', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.profile', verbose_name='پروفایل کاربر'),
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره درخواست')),
                ('currency_type', models.CharField(choices=[('RIAL', 'ریال'), ('GOLD', 'طلا'), ('COIN', 'سکه'), ('DOLLAR', 'دلار')], max_length=10, verbose_name='نوع ارز')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='مقدار درخواستی')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('COMPLETED', 'تکمیل شده')], db_index=True, default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, help_text='دلیل رد یا توضیحات', verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdraw_requests', to='users.bankaccount', verbose_name='حساب بانکی مقصد')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdraw_requests', to='users.profile', verbose_name='پروفایل کاربر')),
                ('related_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_request', to='trading.transaction', verbose_name='تراکنش مرتبط')),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='trading_wit_status_db462a_idx'), models.Index(fields=['profile', '-created_at'], name='trading_wit_profile_0451b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره درخواست')),
                ('receiver_phone', models.CharField(help_text='برای جستجو', max_length=15, verbose_name='شماره تلفن گیرنده')),
                ('currency_type', models.CharField(choices=[('RIAL', 'ریال'), ('GOLD', 'طلا'), ('COIN', 'سکه'), ('DOLLAR', 'دلار')], max_length=10, verbose_name='نوع ارز')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='مقدار')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده')], db_index=True, default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('receiver_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='users.profile', verbose_name='گیرنده')),
                ('receiver_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_receive', to='trading.transaction', verbose_name='تراکنش گیرنده')),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='users.profile', verbose_name='فرستنده')),
                ('sender_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_send', to='trading.transaction', verbose_name='تراکنش فرستنده')),
            ],
            options={
                'verbose_name': 'درخواست انتقال وجه',
                'verbose_name_plural': 'درخواست\u200cهای انتقال وجه',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='trading_tra_status_f71da5_idx'), models.Index(fields=['sender_profile', '-created_at'], name='trading_tra_sender__1f6b6d_idx'), models.Index(fields=['receiver_profile', '-created_at'], name='trading_tra_receive_55e8e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_number'], name='trading_tra_transac_dee57c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['profile', '-created_at'], name='trading_tra_profile_9314fb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='trading_tra_status_6fc988_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'currency_type'], name='trading_tra_transac_910237_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='trading_ord_status_75898c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['profile', '-created_at'], name='trading_ord_profile_194c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status'], name='trading_ord_order_t_019af4_idx'),
        ),
    ]
