# Generated by Django 4.2.25 on 2025-10-15 18:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, help_text='به صورت خودکار از روی نام ساخته می\u200cشود.', unique=True, verbose_name='اسلاگ')),
                ('buy_price', models.DecimalField(decimal_places=0, help_text='قیمتی که ما طلا را از مشتری می\u200cخریم (به ریال)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید ما از مشتری')),
                ('sell_price', models.DecimalField(decimal_places=0, help_text='قیمتی که ما طلا را به مشتری می\u200cفروشیم (به ریال)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت فروش ما به مشتری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال برای معامله')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی قیمت')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('BUY', 'خرید از ما'), ('SELL', 'فروش به ما')], max_length=4, verbose_name='نوع سفارش')),
                ('quantity_grams', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='مقدار (گرم)')),
                ('price_per_gram', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت هر گرم (لحظه ثبت)')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ کل (ریال)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده')], db_index=True, default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.product', verbose_name='محصول')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.profile', verbose_name='پروفایل کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='trading_ord_created_f24bb8_idx'), models.Index(fields=['status'], name='trading_ord_status_a4f93e_idx')],
            },
        ),
    ]
