# Generated by Django 4.2.25 on 2025-10-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, choices=[('GOLD_ABSHODEH', 'طلای آبشده'), ('COIN_FULL', 'سکه تمام غیربانکی'), ('DOLLAR', 'دلار آمریکا')], help_text='کد یکتا برای شناسایی خودکار محصول', max_length=20, null=True, unique=True, verbose_name='کد محصول'),
        ),
    ]
