# Generated by Django 4.2.25 on 2025-10-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='شماره یونیک فاکتور', max_length=50, null=True, unique=True, verbose_name='شماره فاکتور'),
        ),
    ]
