# Generated by Django 4.2.25 on 2025-10-27 18:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_and_more'),
        ('trading', '0007_alter_product_code_non_nullable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='trading_ord_created_f24bb8_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='trading_ord_status_a4f93e_idx',
        ),
        # Skip index renames as they don't exist
        migrations.RemoveField(
            model_name='order',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='زمان تکمیل سفارش', null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='یادداشت\u200cهای داخلی برای ادمین', verbose_name='یادداشت\u200cها'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'خرید از ما'), ('SELL', 'فروش به ما')], help_text='خرید از ما یا فروش به ما', max_length=4, verbose_name='نوع سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=0, help_text='قیمت هر گرم در زمان ثبت سفارش (ریال)', max_digits=12, verbose_name='قیمت هر گرم (لحظه ثبت)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(help_text='محصول مورد معامله', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(help_text='کاربری که این سفارش را ثبت کرده', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.profile', verbose_name='پروفایل کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity_grams',
            field=models.DecimalField(decimal_places=4, help_text='مقدار طلا به گرم', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='مقدار (گرم)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده')], db_index=True, default='PENDING', help_text='وضعیت فعلی سفارش', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, help_text='مبلغ کل سفارش (ریال)', max_digits=15, verbose_name='مبلغ کل (ریال)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت خرید هر گرم از مشتری (ریال)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت خرید ما از مشتری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='آیا این محصول برای معامله فعال است؟', verbose_name='فعال برای معامله'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='نام محصول (مثل: سکه بهار آزادی، طلای 18 عیار)', max_length=100, unique=True, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت فروش هر گرم به مشتری (ریال)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت فروش ما به مشتری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='به صورت خودکار از روی نام ساخته می\u200cشود', unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='trading_ord_status_75898c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['profile', '-created_at'], name='trading_ord_profile_194c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status'], name='trading_ord_order_t_019af4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'name'], name='trading_pro_is_acti_a7c05f_idx'),
        ),
    ]
