# Generated by Django 4.2.25 on 2025-11-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_transaction_withdrawrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='trading_tra_profile_9314fb_idx',
            old_name='trading_tra_profile_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='trading_tra_status_6fc988_idx',
            old_name='trading_tra_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='trading_tra_transac_21b468_idx',
            old_name='trading_tra_transac_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawrequest',
            new_name='trading_wit_profile_0451b6_idx',
            old_name='trading_wit_profile_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawrequest',
            new_name='trading_wit_status_db462a_idx',
            old_name='trading_wit_status_idx',
        ),
    ]
