# Generated by Django 4.2.25 on 2025-11-04 20:16

from django.db import migrations


def add_missing_columns(apps, schema_editor):
    """Add missing columns to Transaction table if they don't exist."""
    with schema_editor.connection.cursor() as cursor:
        # Check existing columns
        cursor.execute("PRAGMA table_info(trading_transaction);")
        columns = [row[1] for row in cursor.fetchall()]
        
        # Add currency column if missing
        if 'currency' not in columns:
            cursor.execute("""
                ALTER TABLE trading_transaction 
                ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT 'RIAL';
            """)
        
        # Add bank_account_id column if missing
        if 'bank_account_id' not in columns:
            cursor.execute("""
                ALTER TABLE trading_transaction 
                ADD COLUMN bank_account_id INTEGER NULL;
            """)
        
        # Add receipt_image column if missing
        if 'receipt_image' not in columns:
            cursor.execute("""
                ALTER TABLE trading_transaction 
                ADD COLUMN receipt_image VARCHAR(100) NULL;
            """)
        
        # Add related_order_id column if missing
        if 'related_order_id' not in columns:
            cursor.execute("""
                ALTER TABLE trading_transaction 
                ADD COLUMN related_order_id INTEGER NULL;
            """)
        
        # Add description column if missing
        if 'description' not in columns:
            cursor.execute("""
                ALTER TABLE trading_transaction 
                ADD COLUMN description TEXT NOT NULL DEFAULT '';
            """)
        
        # Add admin_notes column if missing
        if 'admin_notes' not in columns:
            cursor.execute("""
                ALTER TABLE trading_transaction 
                ADD COLUMN admin_notes TEXT NOT NULL DEFAULT '';
            """)
        
        # Add completed_at column if missing
        if 'completed_at' not in columns:
            cursor.execute("""
                ALTER TABLE trading_transaction 
                ADD COLUMN completed_at DATETIME NULL;
            """)


def reverse_add_missing_columns(apps, schema_editor):
    """Remove columns (reverse operation)."""
    # SQLite doesn't support DROP COLUMN easily, so we'll leave it
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_update_order_status_instant_execution'),
    ]

    operations = [
        migrations.RunPython(add_missing_columns, reverse_add_missing_columns),
    ]
