# Generated by Django 4.2.25 on 2025-11-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_fix_transaction_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='trading_tra_status_6fc988_idx',
            old_name='trading_tra_status_b8c123_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='trading_tra_transac_21b468_idx',
            old_name='trading_tra_transac_a45e67_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawrequest',
            new_name='trading_wit_profile_0451b6_idx',
            old_name='trading_wit_profile_8a9b12_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawrequest',
            new_name='trading_wit_status_db462a_idx',
            old_name='trading_wit_status_c3d456_idx',
        ),
    ]
