# Generated by Django 4.2.25 on 2025-11-04 20:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


def set_default_margins(apps, schema_editor):
    """Set default margin values for existing products based on product type."""
    Product = apps.get_model('trading', 'Product')
    
    # Default margins from PriceCalculator
    GOLD_MARGIN = Decimal('300000')  # 300k Rials
    COIN_MARGIN = Decimal('4500000')  # 4.5M Rials  
    DOLLAR_MARGIN = Decimal('10000')  # 10k Rials
    COIN_WEIGHT_GRAMS = Decimal('8.133')  # Standard coin weight
    
    for product in Product.objects.all():
        if product.product_code == 'gold':
            product.buy_margin = GOLD_MARGIN
            product.sell_margin = GOLD_MARGIN
            product.weight_grams = Decimal('1')
        elif product.product_code == 'coin':
            product.buy_margin = COIN_MARGIN
            product.sell_margin = COIN_MARGIN
            product.weight_grams = COIN_WEIGHT_GRAMS
        elif product.product_code == 'dollar':
            product.buy_margin = DOLLAR_MARGIN
            product.sell_margin = DOLLAR_MARGIN
            product.weight_grams = Decimal('1')
        
        product.save()


def reverse_margins(apps, schema_editor):
    """Reverse operation - set margins back to 0."""
    Product = apps.get_model('trading', 'Product')
    Product.objects.all().update(
        buy_margin=Decimal('0'),
        sell_margin=Decimal('0'),
        weight_grams=Decimal('1')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_rename_trading_tra_status_b8c123_idx_trading_tra_status_6fc988_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price_api',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='آخرین قیمت دریافتی از API (قبل از اعمال مارجین)', max_digits=12, null=True, verbose_name='قیمت پایه از API'),
        ),
        migrations.AddField(
            model_name='product',
            name='buy_margin',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='مارجین خرید از مشتری - این مقدار از قیمت بازار کم می\u200cشود تا قیمت خرید محاسبه شود', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='مارجین خرید (ریال)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_margin',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='مارجین فروش به مشتری - این مقدار به قیمت بازار اضافه می\u200cشود تا قیمت فروش محاسبه شود', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='مارجین فروش (ریال)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='وزن یک واحد محصول به گرم - برای طلا و دلار = 1، برای سکه = 8.133 یا به تناسب نوع سکه', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='وزن واحد (گرم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت محاسبه شده - به صورت خودکار از API + مارجین\u200cها محاسبه می\u200cشود', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت خرید ما از مشتری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت محاسبه شده - به صورت خودکار از API + مارجین\u200cها محاسبه می\u200cشود', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت فروش ما به مشتری'),
        ),
        # Data migration to set default margins for existing products
        migrations.RunPython(set_default_margins, reverse_margins),
    ]
