# Generated by Django 5.1.3 on 2024-11-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_product_base_price_api_product_buy_margin_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='توکن یکتای امن برای احراز هویت', max_length=64, unique=True, verbose_name='توکن دسترسی')),
                ('is_used', models.BooleanField(default=False, help_text='آیا این توکن قبلاً استفاده شده است؟', verbose_name='استفاده شده')),
                ('expires_at', models.DateTimeField(help_text='زمان انقضای توکن', verbose_name='زمان انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='زمان آخرین استفاده از توکن', null=True, verbose_name='آخرین استفاده')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='آدرس IP که از این توکن استفاده کرده', null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, help_text='اطلاعات مرورگر', verbose_name='User Agent')),
                ('profile', models.ForeignKey(help_text='کاربری که این توکن برای اوست', on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='users.profile', verbose_name='پروفایل کاربر')),
            ],
            options={
                'verbose_name': 'توکن دسترسی پورتال',
                'verbose_name_plural': 'توکن‌های دسترسی پورتال',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['token', 'expires_at'], name='trading_por_token_idx'),
                    models.Index(fields=['profile', '-created_at'], name='trading_por_profile_idx'),
                ],
            },
        ),
    ]
