# Generated by Django 4.2.25 on 2025-11-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_add_anigold_product_codes'),
        ('trading', '0016_add_price_history'),
    ]

    operations = [
    ]
