# Generated by Django 4.2.25 on 2025-11-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_add_price_history_model'),
        ('trading', '0017_merge_20251109_2315'),
    ]

    operations = [
    ]
