# Generated by Django 4.2.25 on 2025-11-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_merge_20251111_1947'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricehistory',
            new_name='trading_pri_product_c49885_idx',
            old_name='trading_pri_product_3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='pricehistory',
            new_name='trading_pri_recorde_4e2cf7_idx',
            old_name='trading_pri_recorde_7f8a9b_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(choices=[('gold', 'طلای آبشده'), ('coin', 'سکه تمام'), ('dollar', 'دلار آمریکا')], db_index=True, help_text='کد یکتای محصول برای شناسایی', max_length=20, unique=True, verbose_name='کد محصول'),
        ),
    ]
