# Generated by Django 4.2.25 on 2025-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_rename_created_at_to_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(choices=[('dollar_usa', '💵 دلار آمریکا'), ('euro', '💶 یورو'), ('pound_uk', '💷 پوند انگلیس'), ('yuan_china', '💴 یوان چین'), ('lira_turkey', '🇹🇷 لیر ترکیه'), ('dirham_uae', '🇦🇪 درهم امارات'), ('coin_full', '🪙 سکه غیربانکی (تمام)'), ('coin_half', '🪙 نیم سکه غیربانکی'), ('coin_quarter', '🪙 ربع سکه غیربانکی'), ('gold_abshodeh', '✨ طلای آبشده (18 عیار)')], db_index=True, help_text='کد یکتای محصول برای شناسایی', max_length=20, unique=True, verbose_name='کد محصول'),
        ),
    ]
