# Generated by Django 4.2.25 on 2025-11-11 18:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='ضریب محاسبه قیمت - معمولاً = 1 (سکه\u200cها واحدی هستند، ارزها واحدی، طلا گرمی). فقط در موارد خاص تغییر دهید', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='ضریب واحد'),
        ),
    ]
