# Generated by Django 4.2.25 on 2025-11-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_add_portal_access_token'),
        ('trading', '0022_alter_product_weight_grams'),
    ]

    operations = [
    ]
