# Generated by Django 4.2.25 on 2025-11-12 16:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_merge_20251112_2011'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portalaccesstoken',
            new_name='trading_por_token_0db3f9_idx',
            old_name='trading_por_token_idx',
        ),
        migrations.RenameIndex(
            model_name='portalaccesstoken',
            new_name='trading_por_profile_4249d8_idx',
            old_name='trading_por_profile_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(choices=[('gold', 'طلای آبشده'), ('coin', 'سکه تمام'), ('dollar', 'دلار آمریکا')], db_index=True, help_text='کد یکتای محصول برای شناسایی', max_length=20, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='وزن یک واحد محصول به گرم - برای طلا و دلار = 1، برای سکه = 8.133 یا به تناسب نوع سکه', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='وزن واحد (گرم)'),
        ),
    ]
